### ISSUE TITLE
Questions about the input data

### ISSUE THREAD

**Issue by LabBaxMX-0219** [Chain123/Meta-HAR#1]
Hello, I have a few questions about the source code.

In "data_loader.py", the  "\_\_getitem\_\_" function only returns two values, but when I tracked the code to the file "meta-har.py", the code at line 119(original version) shows that there should be three values to unpack and the error occurred. 
![image](https://user-images.githubusercontent.com/70470574/132938246-65b6f555-8304-44d1-a917-9657701f423d.png)
![image](https://user-images.githubusercontent.com/70470574/132938230-4d08020d-3f71-4989-b18a-d1919f3e97a8.png)

After further checked the source code I know that the third value should be "targets_t", which is missed in "data_loader.py".
![image](https://user-images.githubusercontent.com/70470574/132938283-4675f378-b802-4f1b-ba4f-babdb3f0f98e.png)

I wonder what's the difference between "targets" and "targets_t"?

Thanks！

I'm a student interested in HAR and is currently implementing the "Meta-HAR" paper with HHAR dataset.

Feng Haotian
JiLin University, China
Fenght_99@163.com

**Comment by Chain123** [comment]
Hi  Feng,

First, let me apologize, I haven't had much time to clear the code since it
was published, so there may be a lot of confusion in the repository. As for
your question about the "target_t", This is actually the local label of a
sample for a given user.
Take user h for example, assume that there are 5 global activities (0, 1,
2, 3, 4) and user h has 3 of them in his local dataset (0, 2, 4) however,
the local labels are actually encoded according to the global activity set,
but when we just want to perform activity recognition on each user side we
can only try to distinguish between 0 2 and 4. So we re-labeled the local
samples for each user.
e.g.
sample 1 of user h:
global "label"/"target" :   0 --> local "label_t"/"target_t" :  0
sample 2 of user h:
global  "label"/"target" :   2 --> local "label_t"/"target_t" : 1
sample 3 of user h:
global  "label"/"target" :   4 --> local "label_t"/"target_t" : 2

To get the local label "target_t" you need: 1. figure out the local
activity set (here is (0,2,4)) and 2. build a mapping from the global label
to the local label: (here: {0：0，2：1， 4：2} ).

Hope this can be helpful.

Best
Chenglin

**Comment by LabBaxMX-0219** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    Hi Li,It's excited to get your reply, and maybe I need a bit more help...In "utils.py" there only be "dataloader_gen()", not the "utils.dataloader_gen2()" in "met-har.py" at line 90.Currently I just use "_gen()" as a substitute for the "_gen2()", are there any changes in the latest version?Best,Haotian.
    
     
    
        
                    ***@***.***
        
    
    
        签名由网易邮箱大师定制
    
 

    On 9/12/2021 15:17，Chenglin ***@***.***> wrote： 




Hi  Feng,



First, let me apologize, I haven't had much time to clear the code since it

was published, so there may be a lot of confusion in the repository. As for

your question about the "target_t", This is actually the local label of a

sample for a given user.

Take user h for example, assume that there are 5 global activities (0, 1,

2, 3, 4) and user h has 3 of them in his local dataset (0, 2, 4) however,

the local labels are actually encoded according to the global activity set,

but when we just want to perform activity recognition on each user side we

can only try to distinguish between 0 2 and 4. So we re-labeled the local

samples for each user.

e.g.

sample 1 of user h:

global "label"/"target" :   0 --> local "label_t"/"target_t" :  0

sample 2 of user h:

global  "label"/"target" :   2 --> local "label_t"/"target_t" : 1

sample 3 of user h:

global  "label"/"target" :   4 --> local "label_t"/"target_t" : 2



To get the local label "target_t" you need: 1. figure out the local

activity set (here is (0,2,4)) and 2. build a mapping from the global label

to the local label: (here: {0：0，2：1， 4：2} ).



Hope this can be helpful.



Best

Chenglin

**Comment by LabBaxMX-0219** [comment]
Hi Li,

It's excited to get your reply, and maybe I need a bit more help...

In "utils.py" there only be "dataloader_gen()", not the "utils.dataloader_gen2()" in "met-har.py" at line 90.

Currently I just use "_gen()" as a substitute for the "_gen2()", are there any changes in the latest version?

Best,
Haotian.

**Comment by Chain123** [comment]
Hi Haotian, 

I've updated the utils.py and data_loader.py files to include the dataloader_gen2() function and the heter_data2 class. In the heter_data2 class, the "target_t" is loaded directly from data file ( which is a pickle file). You can do this in data processing step or modify the heter_data2 class accordingly to generate the local label. 

Best

**Comment by Rasha1990** [comment]
> Hello, I have a few questions about the source code.
> 
> In "data_loader.py", the "__getitem__" function only returns two values, but when I tracked the code to the file "meta-har.py", the code at line 119(original version) shows that there should be three values to unpack and the error occurred. ![image](https://user-images.githubusercontent.com/70470574/132938246-65b6f555-8304-44d1-a917-9657701f423d.png) ![image](https://user-images.githubusercontent.com/70470574/132938230-4d08020d-3f71-4989-b18a-d1919f3e97a8.png)
> 
> After further checked the source code I know that the third value should be "targets_t", which is missed in "data_loader.py". ![image](https://user-images.githubusercontent.com/70470574/132938283-4675f378-b802-4f1b-ba4f-babdb3f0f98e.png)
> 
> I wonder what's the difference between "targets" and "targets_t"?
> 
> Thanks！
> 
> I'm a student interested in HAR and is currently implementing the "Meta-HAR" paper with HHAR dataset.
> 
> Feng Haotian JiLin University, China [Fenght_99@163.com](mailto:Fenght_99@163.com)

Hello!

Hope you are fine!

I want to ask you if possible, about pickle files, how did you fix the pickle files issue? because the project call these files several times but couldn't find them.
![error](https://user-images.githubusercontent.com/86659254/135745056-58f439df-d407-47cc-8b5a-d4fc1b35e3eb.png)


thank you in advance.

**Comment by LabBaxMX-0219** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        Hello,
        Apparently you don't have the pickle files, maybe you should find out what the pickle files are used for, and try to generate your own pickle files.I just ignored many of those pickle files as I use HHAR data set. "all_trans_dict" contains the one-hot encoded vectors which helps to map the local(user) label into the global label space.hope this will help~
    
     
    
        
                    ***@***.***
        
    
    
        签名由网易邮箱大师定制
    
 

    On 10/3/2021 ***@***.***> wrote： 






Hello, I have a few questions about the source code.

In "data_loader.py", the "getitem" function only returns two values, but when I tracked the code to the file "meta-har.py", the code at line 119(original version) shows that there should be three values to unpack and the error occurred.  

After further checked the source code I know that the third value should be "targets_t", which is missed in "data_loader.py". 

I wonder what's the difference between "targets" and "targets_t"?

Thanks！

I'm a student interested in HAR and is currently implementing the "Meta-HAR" paper with HHAR dataset.

Feng Haotian JiLin University, China ***@***.***



Hello!

Hope you are fine!

I want to ask you if possible, about pickle files, how did you fix the pickle files issue? because the project call these files several times but couldn't find them.



thank you in advance.

**Comment by LabBaxMX-0219** [comment]
@Rasha1990 

Hello,

Apparently you don't have the pickle files, maybe you should find out what the pickle files are used for, and try to generate your own pickle files.

I just ignored many of those pickle files as I use HHAR data set. 

"all_trans_dict" contains the one-hot encoded vectors which help to map the local(user) label into the global label space.
![1](https://user-images.githubusercontent.com/70470574/135745967-1b62f23b-3383-4918-9f16-312a0d23f670.png)
![2](https://user-images.githubusercontent.com/70470574/135745968-acd72ca0-b7c2-4d92-9b7a-7bb5816d1107.png)

hope this will help~ 

> > Hello, I have a few questions about the source code.
> > In "data_loader.py", the "**getitem**" function only returns two values, but when I tracked the code to the file "meta-har.py", the code at line 119(original version) shows that there should be three values to unpack and the error occurred. ![image](https://user-images.githubusercontent.com/70470574/132938246-65b6f555-8304-44d1-a917-9657701f423d.png) ![image](https://user-images.githubusercontent.com/70470574/132938230-4d08020d-3f71-4989-b18a-d1919f3e97a8.png)
> > After further checked the source code I know that the third value should be "targets_t", which is missed in "data_loader.py". ![image](https://user-images.githubusercontent.com/70470574/132938283-4675f378-b802-4f1b-ba4f-babdb3f0f98e.png)
> > I wonder what's the difference between "targets" and "targets_t"?
> > Thanks！
> > I'm a student interested in HAR and is currently implementing the "Meta-HAR" paper with HHAR dataset.
> > Feng Haotian JiLin University, China [Fenght_99@163.com](mailto:Fenght_99@163.com)
> 
> Hello!
> 
> Hope you are fine!
> 
> I want to ask you if possible, about pickle files, how did you fix the pickle files issue? because the project call these files several times but couldn't find them. ![error](https://user-images.githubusercontent.com/86659254/135745056-58f439df-d407-47cc-8b5a-d4fc1b35e3eb.png)
> 
> thank you in advance.

**Comment by Rasha1990** [comment]
Hello !

Hope you are fine!

Thank you so much for your response!

Actually, I want to use the HHAR dataset instead of pickles, but I find the
code use pickles everywhere instead of the data. even functions use the
pickles files. When i tried to use the data instead I have got a lot of
errors. Are there any suggestions on how can I fix the code to use the
dataset?

Actually, I want to develop the code, and I have some idea but now just try
to make it run.

thank you in advance.
