### ISSUE TITLE
The .pickle files are missing

### ISSUE THREAD

**Issue by Rasha1990** [Chain123/Meta-HAR#2]
![error](https://user-images.githubusercontent.com/86659254/135711081-394373b5-18e7-4180-811b-97faa7f5cb76.png)

Hello! 

Hope you are fine!

Firstly, thank you for making this code open source.

I want to ask you two questions if possible:
1-I tried to run the code, by running met-har.py but got an error, that the code call pickles files but the code couldn't find these files. I tried to search these files online but could not find them. For example, in line 31 of the met-har.py file 
all_trans_dict = utils.load_pickle("/data/ceph/seqrec/fl_data/www21/source/trans_dict_all.pickle"). The code use this path (/data/ceph/seqrec/fl_data/www21/) several times to call some pickles files,  but where can i find this dataset. Note: I already downloaded all the datasets mentioned at the readme file, but couldn't find the pickles files.

2-what is the use of pickle files? I find out these files are used instead of dataset, Is that right?

Thank you in advance 

I am PhD student, I want to build a new HAR system.

**Comment by Chain123** [comment]
Hi, 

I will clear and update the code after a recent DDL (about 10 days later).  Sorry for the inconvenience and delay.

**Comment by Rasha1990** [comment]
hello!

Ok, thank you so much :)

**Comment by Rasha1990** [comment]
Hi!

Hope you are fine!

I want to say, thank you so much for your big help☺

**Comment by Chain123** [comment]
It's great to be helpful to you, my pleasure.

Best wishes
Chenglin

**Comment by Rasha1990** [comment]
Yes, it is helpful to me. Thank you so much ☺
